### ISSUE TITLE
calculate un-encrypted file size in `verify`

### ISSUE THREAD

**Issue by blankdots** [neicnordic/sda-pipeline#142]
we should calculate un-encrypted file size in `verify`

Problem is which column to use to store in db. `inbox_filesize` seem unnecessary at the moment and could be used

**Comment by pontus** [comment]
I'm a bit uncertain what concerns there are for modifying the DB schema (except compatibility with the legacy code). I'd prefer a more descriptive name (like decrypted_filesize, analogue to decrypted_file_checksum).

**Comment by blankdots** [comment]
I am all for modifying db schema as well. adding a column should be enough 
but it seems we need to add it in several places:
- https://github.com/neicnordic/LocalEGA-db/blob/master/initdb.d/01_main.sql#L71
- and several of the views:
   - https://github.com/neicnordic/LocalEGA-db/blob/master/initdb.d/01_main.sql#L296
   - https://github.com/neicnordic/LocalEGA-db/blob/master/initdb.d/01_main.sql#L169
   - https://github.com/neicnordic/LocalEGA-db/blob/master/initdb.d/03_ebi.sql#L6
