### ISSUE TITLE
Messages, s3 and eventual consistency

### ISSUE THREAD

**Issue by pontus** [neicnordic/sda-pipeline#143]
Since s3 is eventually consistent, it's quite possible that we get messages for a file in inbox and when we try to access. I believe this (or some similar issue) is currently seen in #141.

The fix for that will likely be different, but for ingestion as well as verification, we should probably handle the case that the message arrives before the s3 provider gets its things in order - that is, we should not treat a failure of getting a filesize or reader as fatal but rather see that as that we should retry (up to a certain limit).

I'm not sure how that is best done through the broker (requeue or send a new message) and what can be done (include a counter? Do we have a timestamp we can look at?) but we will probably need to do something.

**Comment by jbygdell** [comment]
We have this in verify, might need to add it to ingest or incorporate it in `GetFileSize` in storage.go
https://github.com/neicnordic/sda-pipeline/blob/11eea42816089b137f76dd5b58fdaab9f1bac985/cmd/verify/verify.go#L136:L142

**Comment by pontus** [comment]
Something like that might be best, yes. I'd vote for implementing it in storage.go with a maximum retry time of five minutes or so, I think.

**Comment by pontus** [comment]
Fixed by #141.
