### ISSUE TITLE
Handle database connection issues

### ISSUE THREAD

**Issue by pontus** [neicnordic/sda-pipeline#158]
Make sure we handle everything correctly if there are issues with the connection.

**Comment by jbygdell** [comment]
`time="2020-10-27T10:59:45Z" level=error msg="write tcp 172.26.0.9:35144->172.26.0.2:5432: write: broken pipe"`

This is what we get if the db connection closes

**Comment by pontus** [comment]
I think this is fixed now (by #175 and #162).
