### ISSUE TITLE
Run all static code tests on PUSH

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/sda-pipeline#21]
That means go ver, go lint gofmt and so on

**Comment by pontus** [comment]
These are likely all covered covered by the golangci-lint which runs on PRs now.

It can easily be run on every push but there were 15 existing complaints (and for PRs, the action we use can report only new issues whereas the same is not true when run on push).

I opted for waiting with that as fixing the existing complaints would touch all over and cause conflicts for everyone else. If we pursue this, it can easily be fixed when there's a lull.
