### ISSUE TITLE
Add `sync/backup` service to test suite

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/sda-pipeline#216]
DoD: Ingestion test run with the `sync/backup` service doing backup of file from archive before `finalize` receive the message to start it's work. `sync/backup` listens to `accessionIDs` and publishes with the routing key so that the message ends up in the queue `finalize` listens to. `finalize` *can not* listen to `accessionIDs` in this scenario.

**Comment by pontus** [comment]
Fixed by #229
