### ISSUE TITLE
Create dataset id that is not dependent on path

### ISSUE THREAD

**Issue by dbampalikis** [neicnordic/sda-pipeline#294]
Currently the orchestrator is creating dataset ids based on the path of the file. That needs to change, given that files might be uploaded in the same folder.

Ideas:
- Deploy a service that gets the message from completed and upon user interaction it creates the dataset id 
The dataset id will be given (possibly from the data stewards - DOI)

Inputs: 
1. File paths as they are defined in the metadata
2. DOI for the specific dataset
3. Submitter's username

Output:
Message for mapper service

Could even be a Kubernetes job

Note: The dataset id creation is not an automatic process

**Comment by jbygdell** [comment]
### Example of  a solution:
A script that reads a file containing filepaths to include
DatasetID as variable.
MQ credentials as variables.
Uses CURL to generate messages to a forwarded MQ connection.

**Comment by blankdots** [comment]
should this be a https://github.com/neicnordic/sda-orchestration issue ?

I remember i changed that to be dependant on path and user id: https://github.com/neicnordic/sda-orchestration/blob/master/sda_orchestrator/utils/id_ops.py#L31-L34

In any case if there is a metadata service the dataset ID will be associated there. 
we @ CSC plan to use the https://github.com/CSCfi/metadata-submitter to handle that long term (well at least at the moment as plans might change).

**Comment by jbygdell** [comment]
Long term it should be handled by the metadata service, right  now we needed to have a solution in place for the short term as a stop gap.
