### ISSUE TITLE
Remove verified files from inbox

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/sda-pipeline#357]
Dod:
* When a file has been verified OK it should be removed from the inbox.

**Comment by blankdots** [comment]
it sounds to me like this should this be handled by a different service :thinking: e.g. `cleaner` or `sweep` service
In my mind we will be sending a message from finalize (i would prefer it rather than backup, as some installations might not require backup) to this new service.

**Comment by blankdots** [comment]
a cleaner service might be a bit too much for this and to difficult to manage, we can create a separate tool that helps with cleaning the necessary paths, database or queues
