### ISSUE TITLE
DB TLS configuration

### ISSUE THREAD

**Issue by dtitov** [neicnordic/sda-pipeline#40]
https://github.com/neicnordic/sda-pipeline/blob/997cfd6d429167ea58c708bbf45031d64f54dac0/internal/config/config.go#L247

Right now only `verify-full` mode is supported as optional. We need to support all SSL modes, or, at least, `require`.

**Comment by jbygdell** [comment]
TL;DR all sslModes are supported.

If you look closely you'll see that when `sslMode == verify-full` we make sure that we have the client certificates. In all other cases we rely on our CAroot certificates.

**Comment by dtitov** [comment]
Yeah, my bad. Still. line 248 should be removed (as we set `db.SslMode` before, at line 244).

**Comment by dtitov** [comment]
Actually, there's a discrepancy here: at line 244 we read `db.sslmode`, but at line 248 we read `db.sslMode`.

**Comment by jbygdell** [comment]
L248 should be made optional as `sslMode` has a default value in the DB module.
And it should be `sslMode` since that is defined in the DB config struct.

**Comment by dtitov** [comment]
My point is that `db.sslmode` != `db.sslMode` (`m` is capitalized in the latter). Is it intentional?

**Comment by jbygdell** [comment]
It should match what's in the struct i.e `sslMode` the all lowecase one is wrong
