### ISSUE TITLE
Fix MQ connectivity

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/sda-pipeline#412]
If the connection to the MQ stalls, it will not be repoened unless the process is restarted.
relevant error mesage: `reason: Exception (504) Reason: \"channel/connection is not open\")"`

A/C: 
- [ ] create testcase for MQ reconnects
- [ ] check MQ connection before sending a message and reconnect if needed.

**Comment by pontus** [comment]
Some comments in https://github.com/neicnordic/sda-pipeline/pull/517

Not sure what's going on here really (why the `NotifyClose`, e.g. https://github.com/neicnordic/sda-pipeline/blob/master/internal/broker/broker.go#L237 doesn't trigger). 

It doesn't seem likely, but possibly I could see this happen if the broker pod goes away (so the new one gets a new IP and nothing responds on the old IP) before the connection finally times out (after up to two hours).

**Comment by jbygdell** [comment]
`NotifyClose` works for `connection` events but not for `channel` events, and those can not be tested either since there is no way to only close the channel from the MQ server side.

**Comment by jbygdell** [comment]
The entire MQ handling really needs to be reworked from the bottom up in order to be able to solve the reconnect issue.

**Comment by pontus** [comment]
For now, I mostly don't see why the `channel` goes wonky if the `connection` is still fine, so what's actually going wrong.

**Comment by jbygdell** [comment]
A connection can have multiple channels

**Comment by pontus** [comment]
Yes, so is this a RabbitMQ server bug then? :shrug: 

(To me it feels like any externally inflicted issue would be on the `connection` level.)

**Comment by jbygdell** [comment]
The root problem is that as the code is written now we can't recreate a dropped channel from the services.
