### ISSUE TITLE
Writing to database problem

### ISSUE THREAD

**Issue by a-ghanem** [neicnordic/sda-pipeline#432]
When the `ingest` service tries to write to the database that the uploaded file is marked as ready, the connection is dropped and the following error message is logged in the database
```
could not receive data from client: Connection reset by peer
```
I am using the following image versions:
1. ghcr.io/neicnordic/sda-db:v1.4.5
2. ghcr.io/neicnordic/sda-pipeline:v0.3.34

I tried using `tcpdump` to capture the packets to see if it is related to any network connectivity issues and no packets were captured.

**Comment by norling** [comment]
is this still relevant?
