### ISSUE TITLE
Queues hang when there is no permission to publish

### ISSUE THREAD

**Issue by dbampalikis** [neicnordic/sda-pipeline#480]
If the configuration of the RabbitMQ doesn't give access to a user to publish to a specific exchange, the service hangs and requires restart.

For example [here](https://github.com/neicnordic/sda-pipeline/blob/4cf199601d8bf9161c975bc301ba71a75a059821/cmd/ingest/ingest.go#L453) if the user doesn't have access to publish to the exchange, the message is not unacked and the next messages are not taken care of

**Comment by blankdots** [comment]
i think we might be reaching a deadlock here, which i noticed also in other use case e.g. a ack is not sent by the service and the MQ timesout, causing a service to reach a deadlock. Not sure if the solution here https://github.com/rabbitmq/amqp091-go/pull/123 would solve it :thinking:

**Comment by nanjiangshu** [comment]
need to be verified
